### ISSUE TITLE
Zuul2.0实现微服务网关？真的是Zuul2.0嘛

### ISSUE THREAD

**Issue by publisherfk** [DespairYoke/java-advance#1]
我看了下你写的maven依赖
`<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-starter-netflix-zuul</artifactId>
</dependency>`
这个依赖的只有zuul1系列，spring cloud原生不会再集成zuul2.0，你也可以看看这个项目的maven dependencies

**Comment by DespairYoke** [comment]
我用的是2.1.0 官网只是说不在维护这个项目

**Comment by DespairYoke** [comment]
> 我看了下你写的maven依赖
> `<dependency> <groupId>org.springframework.cloud</groupId> <artifactId>spring-cloud-starter-netflix-zuul</artifactId> </dependency>`
> 这个依赖的只有zuul1系列，spring cloud原生不会再集成zuul2.0，你也可以看看这个项目的maven dependencies

我用的是2.1.0 官网只是说不在维护这个项目

**Comment by publisherfk** [comment]
你给的demo里面也看不出你用了zuul2.1.0

**Comment by DespairYoke** [comment]
> 你给的demo里面也看不出你用了zuul2.1.0
根据父依赖继承的 你可以看下父依赖的版本
